name: 'Auto NLP Action'
description: 'Линтинг, запуск и загрузка ноутбука на Github Pages'
inputs:
  home-task-filename:
    description: 'Имя Jupyter-ноутбука, в котором хранится задание'
    required: true
    default: 'task.ipynb'


runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
      
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.12'

    - uses: py-actions/py-dependency-install@v4
      with:
        path: ${{ github.head_ref }}/requirements.txt
    
    - uses: yaananth/run-notebook@v2
      with:
        notebook: "${{ github.head_ref }}/task.ipynb"
        params: "PATHTOPARAMS.json"
        isReport: False
        poll: True

    - name: Tar files
      shell: sh
      run: |
        cd ${{ RUNNER.temp }}/nb-runner/
        mkdir ${{ github.head_ref }}
        mv task.html ${{ github.head_ref }}/index.html
        tar --dereference --hard-dereference -cvf artifact.tar ${{ github.head_ref }}/
    
    - uses: actions/upload-pages-artifact@v2
      if: always()
      with:
        name: github-pages
        path: ${{ RUNNER.temp }}/nb-runner/

    - name: Download artifact
      uses: actions/download-artifact@v3
      env:
        RUNNER: ${{ toJson(runner) }}