name: Jupyter Notebook

on: [pull_request, workflow_dispatch]

permissions:
    pages: write
    id-token: write

jobs:
  check-home-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verify-task
        uses: ./
        with:
            home-task-filename: task.ipynb