name: Jupyter Notebook

on: [pull_request, workflow_dispatch]


jobs:
  check-home-task:
    permissions:
        pages: write
        id-token: write
    
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verify-task
        uses: danilkladnitsky/auto-nlp-action
        with:
            home-task-filename: task.ipynb